---
server:
  port: 8761

spring:
  main:
    banner-mode: off
  application:
    name: eureka-server

eureka:
  instance:
    #Host donde se esta corriendo el servidor
    hostname: https://s10-14-ft-eurekaserver.azurewebsites.net
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
...