---
app:
  jwt:
    expiration-in-minute: 5
    secret: RandomSecretKey123456789!RandomSecretKey123456789!RandomSecretKey123456789!
spring:
  application:
    name: security
  main:
    #Desactivo el Banner de Spring Boot de consola
    banner-mode: off
  datasource:
    url: jdbc:mysql://20.121.214.190:3307/account-db
    username: root
    password: nocountry#2023
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #Connect kafka
  kafka:
    template:
      default-topic: account-topic

logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

service:
  security:
    secure-key-username: NoCountryKeySecureUsername
    secure-key-password: NoCountryKeySecurePassword!

server:
  error:
    include-stacktrace: never
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
...